name: 💡 Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered?
      placeholder: I've also thought about...

  - type: textarea
    id: api
    attributes:
      label: Proposed API
      description: Show how the feature would be used
      render: rust
      placeholder: |
        // Example usage
        let widget = Widget::new()
            .with_feature(value);

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe real-world use cases
      placeholder: This would be useful for...
    validations:
      required: true

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change?
      description: Would this be a breaking change?
      options:
        - "No"
        - "Yes"
        - "Not sure"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context or screenshots
      placeholder: Mockups, diagrams, related issues, etc.

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: This is not a duplicate feature request
          required: true
        - label: I am willing to help implement this
          required: false

